language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - npm i
  - npm i -g jest codecov eslint
after_success:
  - snyk monitor
jobs:
  include:
    - stage: test
      script:
      - npm run lint
      - snyk auth $SNYK_TOKEN
      - npm test
      - codecov
    - stage: deploy
      script: npm run semantic-release
      node_js: 'node'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  # - install
  - test
  - name: deploy
    if: branch = master