language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - npm i
  - npm i -g jest codecov eslint
after_success:
  - snyk monitor
jobs:
  include:
    - stage: test
      node_js: 'lts/*'
      script:
        - npm run lint
        - snyk auth $SNYK_TOKEN
        - npm test
        - codecov
    - stage: release
      node_js: 'node'
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: release
    if: branch = master
