language: node_js
os: linux
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
install:
  - npm ci
  - npm i -g jest codecov eslint
script:
  - npm run lint
  - snyk auth $SNYK_TOKEN
  - npm test
  - codecov
after_success:
  - snyk monitor
jobs:
  include:
    - stage: release
      node_js: 'stable'
      script: skip
      deploy:
        provider: script
        script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: test
  - name: release
    if: branch = master
