language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '9'
  - '8'
  - '6'
install:
  - npm i
  - npm i -g jest codecov eslint conventional-changelog
script:
  - npm run lint
  - npm test
  - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
